apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz  # rootpassword123
  mysql-database: ZW50cnl0cmFja2VyX2Ri       # entrytracker_db
  mysql-user: YXBwX3VzZXI=                  # app_user
  mysql-password: YXBwX3Bhc3N3b3Jk          # app_password
