name: EntryTracker CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  entrytracker-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the application in background
        run: |
          nohup python app.py &
          sleep 5

      - name: Unit test with curl
        run: curl --fail http://localhost:5000 || exit 1

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/riki-dev-1/entrytracker:latest .
      - name: Start E2E environment with docker-compose
        run: |
          docker compose up -d
          sleep 10
          curl --fail http://localhost:5000 || exit 1
          docker compose down
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/riki-dev-1/entrytracker:latest


          




